<?php


$resTv = \CIBlockElement::GetList(
  array(),
  array(
    "IBLOCK_ID" => \MIT\IBLOCK_ID_CATALOG,
    'SECTION_GLOBAL_ACTIVE' => 'Y',
    "INCLUDE_SUBSECTIONS" => "Y",
    array(
      "LOGIC" => "OR",
      array("XML_ID" => $ProductModel->getListXML_ID($_REQUEST['q'])),
      array("%NAME" => $_REQUEST['q']),
      array("%PROPERTY_78_VALUE" => $_REQUEST['q']),
      array("%PROPERTY_79_VALUE" => $_REQUEST['q']),
      array("%PROPERTY_54_VALUE" => $_REQUEST['q']),
    ),
  ),
  false,
  array(/*"nTopCount" => 50*/),
  array('ID', 'NAME', 'DETAIL_PAGE_URL', 'PREVIEW_PICTURE', 'DETAIL_PICTURE', 'PROPERTY_*')
);

while ($obTv = $resTv->GetNext())
  $arTv[$obTv["ID"]] = $obTv["ID"];


$GLOBALS["arrFilterSearch"]["ID"] = $arTv;

# 888888888888888888888888888888888888888888888888888888888888888888888888888
# 888888888888888888888888888888888888888888888888888888888888888888888888888
# 888888888888888888888888888888888888888888888888888888888888888888888888888

$intSectionID = $APPLICATION->IncludeComponent(
  "bitrix:catalog.section",
  "cat_prod_list",
  array(
    "FILTER_NAME" => "arrFilterSearch",
    "IBLOCK_TYPE" => "1c_catalog",
    "IBLOCK_ID" => "9",
    "ELEMENT_SORT_FIELD" => "name",
    "ELEMENT_SORT_ORDER" => "desc",
    "ELEMENT_SORT_FIELD2" => "id",
    "ELEMENT_SORT_ORDER2" => "desc",
    "PROPERTY_CODE" => array(
      0 => "",
      1 => "NEWPRODUCT",
      2 => "SALELEADER",
      3 => "SPECIALOFFER",
      4 => "",
    ),
    "PROPERTY_CODE_MOBILE" => array(),
    "META_KEYWORDS" => "-",
    "META_DESCRIPTION" => "-",
    "BROWSER_TITLE" => "NAME",
    "SET_LAST_MODIFIED" => "N",
    "INCLUDE_SUBSECTIONS" => "Y",
    "BASKET_URL" => "/personal/cart/",
    "ACTION_VARIABLE" => "action",
    "PRODUCT_ID_VARIABLE" => "id",
    "SECTION_ID_VARIABLE" => "SECTION_ID",
    "PRODUCT_QUANTITY_VARIABLE" => "quantity",
    "PRODUCT_PROPS_VARIABLE" => "prop",
    "CACHE_TYPE" => "N",
    "CACHE_TIME" => "36000000",
    "CACHE_FILTER" => "N",
    "CACHE_GROUPS" => "N",
    "SET_TITLE" => "Y",
    "MESSAGE_404" => "",
    "SET_STATUS_404" => "Y",
    "SHOW_404" => "N",
    "FILE_404" => NULL,
    "DISPLAY_COMPARE" => "N",
    "PAGE_ELEMENT_COUNT" => "6",
    "LINE_ELEMENT_COUNT" => "3",
    "PRICE_CODE" => array(
      0 => "Розничные продажи",
    ),
    "USE_PRICE_COUNT" => "N",
    "SHOW_PRICE_COUNT" => "1",
    "PRICE_VAT_INCLUDE" => "Y",
    "USE_PRODUCT_QUANTITY" => "Y",
    "ADD_PROPERTIES_TO_BASKET" => "Y",
    "PARTIAL_PRODUCT_PROPERTIES" => "N",
    "PRODUCT_PROPERTIES" => array(),
    "DISPLAY_TOP_PAGER" => "N",
    "DISPLAY_BOTTOM_PAGER" => "Y",
    "PAGER_TITLE" => "Товары",
    "PAGER_SHOW_ALWAYS" => "N",
    "PAGER_TEMPLATE" => "pagen",
    "PAGER_DESC_NUMBERING" => "N",
    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
    "PAGER_SHOW_ALL" => "N",
    "PAGER_BASE_LINK_ENABLE" => "N",
    "PAGER_BASE_LINK" => NULL,
    "PAGER_PARAMS_NAME" => NULL,
    "LAZY_LOAD" => "N",
    "MESS_BTN_LAZY_LOAD" => "Показать ещё",
    "LOAD_ON_SCROLL" => "N",
    "OFFERS_CART_PROPERTIES" => "",
    "OFFERS_FIELD_CODE" => array(
      0 => "NAME",
      1 => "PREVIEW_PICTURE",
      2 => "DETAIL_PICTURE",
      3 => "",
    ),
    "OFFERS_PROPERTY_CODE" => array(
      0 => "MORE_PHOTO",
      1 => "ARTNUMBER",
      2 => "COLOR_REF",
      3 => "SIZES_SHOES",
      4 => "SIZES_CLOTHES",
      5 => "",
    ),
    "OFFERS_SORT_FIELD" => "sort",
    "OFFERS_SORT_ORDER" => "desc",
    "OFFERS_SORT_FIELD2" => "id",
    "OFFERS_SORT_ORDER2" => "desc",
    "OFFERS_LIMIT" => "0",
    "SECTION_ID" => "",
    "SECTION_CODE" => "",
    "SECTION_URL" => "/catalog/#SECTION_CODE_PATH#/",
    "DETAIL_URL" => "/catalog/#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
    "USE_MAIN_ELEMENT_SECTION" => "Y",
    "CONVERT_CURRENCY" => "N",
    "CURRENCY_ID" => NULL,
    "HIDE_NOT_AVAILABLE" => "N",
    "HIDE_NOT_AVAILABLE_OFFERS" => "L",
    "LABEL_PROP" => array(
      0 => "PRIMENIMOST",
    ),
    "LABEL_PROP_MOBILE" => array(
      0 => "PRIMENIMOST",
    ),
    "LABEL_PROP_POSITION" => "top-left",
    "ADD_PICT_PROP" => "MORE_PHOTO",
    "PRODUCT_DISPLAY_MODE" => "Y",
    "PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
    "PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
    "ENLARGE_PRODUCT" => "STRICT",
    "ENLARGE_PROP" => "",
    "SHOW_SLIDER" => "N",
    "SLIDER_INTERVAL" => "3000",
    "SLIDER_PROGRESS" => "N",
    "OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
    "OFFER_TREE_PROPS" => "",
    "PRODUCT_SUBSCRIPTION" => "Y",
    "SHOW_DISCOUNT_PERCENT" => "Y",
    "DISCOUNT_PERCENT_POSITION" => "bottom-right",
    "SHOW_OLD_PRICE" => "Y",
    "SHOW_MAX_QUANTITY" => "Y",
    "MESS_SHOW_MAX_QUANTITY" => "Наличие",
    "RELATIVE_QUANTITY_FACTOR" => "",
    "MESS_RELATIVE_QUANTITY_MANY" => "",
    "MESS_RELATIVE_QUANTITY_FEW" => "",
    "MESS_BTN_BUY" => "Купить",
    "MESS_BTN_ADD_TO_BASKET" => "В корзину",
    "MESS_BTN_SUBSCRIBE" => "Подписаться",
    "MESS_BTN_DETAIL" => "Подробнее",
    "MESS_NOT_AVAILABLE" => "Нет в наличии",
    "MESS_BTN_COMPARE" => "Сравнение",
    "USE_ENHANCED_ECOMMERCE" => "N",
    "DATA_LAYER_NAME" => "",
    "BRAND_PROPERTY" => "",
    "TEMPLATE_THEME" => "blue",
    "ADD_SECTIONS_CHAIN" => "Y",
    "ADD_TO_BASKET_ACTION" => "ADD",
    "SHOW_CLOSE_POPUP" => "Y",
    "COMPARE_PATH" => "/catalog/compare/",
    "COMPARE_NAME" => NULL,
    "USE_COMPARE_LIST" => "Y",
    "BACKGROUND_IMAGE" => "-",
    "COMPATIBLE_MODE" => "N",
    "DISABLE_INIT_JS_IN_COMPONENT" => "N",
    "COMPONENT_TEMPLATE" => "cat_prod_list",
    "SECTION_USER_FIELDS" => array(
      0 => "",
      1 => "",
    ),
    "SHOW_ALL_WO_SECTION" => "N",
    "CUSTOM_FILTER" => "{\"CLASS_ID\":\"CondGroup\",\"DATA\":{\"All\":\"AND\",\"True\":\"True\"},\"CHILDREN\":[]}",
    "RCM_TYPE" => "personal",
    "RCM_PROD_ID" => $_REQUEST["PRODUCT_ID"],
    "SHOW_FROM_SECTION" => "N",
    "SEF_MODE" => "N",
    "AJAX_MODE" => "N",
    "AJAX_OPTION_JUMP" => "N",
    "AJAX_OPTION_STYLE" => "Y",
    "AJAX_OPTION_HISTORY" => "N",
    "AJAX_OPTION_ADDITIONAL" => "",
    "SET_BROWSER_TITLE" => "Y",
    "SET_META_KEYWORDS" => "Y",
    "SET_META_DESCRIPTION" => "Y"
  ),
  $component
);
