<?php

if (mb_strlen($_REQUEST['q']) >= 3) {

  $resTv = \CIBlockElement::GetList(
    array(),
    array(
      "IBLOCK_ID" => '4',
      'SECTION_GLOBAL_ACTIVE' => 'Y',
      "INCLUDE_SUBSECTIONS" => "Y",
      array(
        "LOGIC" => "OR",
        array("NAME" => "{$_REQUEST['q']}%"),
        // array("%PROPERTY_54_VALUE" => $_REQUEST['q']),
      ),
    ),
    false,
    [], //array("nTopCount" => 50),
    array('ID', 'NAME', 'DETAIL_PAGE_URL', 'PREVIEW_PICTURE', 'DETAIL_PICTURE', 'PROPERTY_*')
  );

  while ($obTv = $resTv->GetNext())
    $arTv[$obTv["ID"]] = $obTv["ID"];


  $GLOBALS["arrFilterSearch"]["ID"] = $arTv;

  $intSectionID =
    count($arTv)
    && $APPLICATION->IncludeComponent(
      "bitrix:catalog.section",
      "searched",
      [
        'IBLOCK_TYPE' => 'catalog',
        'IBLOCK_ID' => '4',
        'ELEMENT_SORT_FIELD' => 'sort',
        'ELEMENT_SORT_ORDER' => 'asc',
        'ELEMENT_SORT_FIELD2' => 'id',
        'ELEMENT_SORT_ORDER2' => 'desc',
        'COLUMN_PROPERTY_ID' => [
          0 => 14,
          1 => 315,
          2 => 417,
          3 => 434,
          4 => 540,
          5 => 549,
        ],
        'PROPERTY_CODE' => [],
        'PROPERTY_CODE_MOBILE' => NULL,
        'META_KEYWORDS' => '-',
        'META_DESCRIPTION' => '-',
        'BROWSER_TITLE' => '-',
        'SET_LAST_MODIFIED' => 'Y',
        'INCLUDE_SUBSECTIONS' => 'Y',
        'BASKET_URL' => '/personal/basket/',
        'ACTION_VARIABLE' => 'action',
        'PRODUCT_ID_VARIABLE' => 'id',
        'SECTION_ID_VARIABLE' => 'SECTION_ID',
        'PRODUCT_QUANTITY_VARIABLE' => 'quantity',
        'PRODUCT_PROPS_VARIABLE' => 'prop',
        "FILTER_NAME" => "arrFilterSearch",
        'CACHE_TYPE' => 'A',
        'CACHE_TIME' => 0,
        'CACHE_FILTER' => 'Y',
        'CACHE_GROUPS' => 'Y',
        'SET_TITLE' => 'Y',
        'MESSAGE_404' => '',
        'SET_STATUS_404' => 'N',
        'SHOW_404' => 'Y',
        'FILE_404' => NULL,
        'DISPLAY_COMPARE' => 'Y',
        'PAGE_ELEMENT_COUNT' => '30',
        'LINE_ELEMENT_COUNT' => '3',
        'PRICE_CODE' => [
          0 => 'BASE',
        ],
        'USE_PRICE_COUNT' => 'N',
        'SHOW_PRICE_COUNT' => '1',
        'PRICE_VAT_INCLUDE' => 'Y',
        'USE_PRODUCT_QUANTITY' => 'N',
        'ADD_PROPERTIES_TO_BASKET' => 'Y',
        'PARTIAL_PRODUCT_PROPERTIES' => 'N',
        'PRODUCT_PROPERTIES' => [],
        'DISPLAY_TOP_PAGER' => 'N',
        'DISPLAY_BOTTOM_PAGER' => 'Y',
        'PAGER_TITLE' => 'Товары',
        'PAGER_SHOW_ALWAYS' => 'N',
        'PAGER_TEMPLATE' => '.default',
        'PAGER_DESC_NUMBERING' => 'N',
        'PAGER_DESC_NUMBERING_CACHE_TIME' => '86400',
        'PAGER_SHOW_ALL' => 'N',
        'PAGER_BASE_LINK_ENABLE' => 'N',
        'PAGER_BASE_LINK' => NULL,
        'PAGER_PARAMS_NAME' => NULL,
        'LAZY_LOAD' => 'N',
        'MESS_BTN_LAZY_LOAD' => NULL,
        'LOAD_ON_SCROLL' => 'N',
        'OFFERS_CART_PROPERTIES' => [],
        'OFFERS_FIELD_CODE' => NULL,
        'OFFERS_PROPERTY_CODE' => [],
        'OFFERS_SORT_FIELD' => NULL,
        'OFFERS_SORT_ORDER' => NULL,
        'OFFERS_SORT_FIELD2' => NULL,
        'OFFERS_SORT_ORDER2' => NULL,
        "OFFERS_LIMIT" => "0",
        "SECTION_ID" => "",
        "SECTION_CODE" => "",
        'SECTION_URL' => '/catalog/#SECTION_CODE_PATH#/',
        'DETAIL_URL' => '/catalog/#SECTION_CODE_PATH#/#ELEMENT_CODE#/',
        'USE_MAIN_ELEMENT_SECTION' => 'N',
        'CONVERT_CURRENCY' => 'N',
        'CURRENCY_ID' => NULL,
        'HIDE_NOT_AVAILABLE' => 'N',
        'HIDE_NOT_AVAILABLE_OFFERS' => 'N',
        'LABEL_PROP' => '',
        'LABEL_PROP_MOBILE' => NULL,
        'LABEL_PROP_POSITION' => NULL,
        'ADD_PICT_PROP' => '-',
        'PRODUCT_DISPLAY_MODE' => NULL,
        'PRODUCT_BLOCKS_ORDER' => 'price,props,sku,quantityLimit,quantity,buttons',
        'PRODUCT_ROW_VARIANTS' => '[{\'VARIANT\':\'2\',\'BIG_DATA\':false},{\'VARIANT\':\'2\',\'BIG_DATA\':false},{\'VARIANT\':\'2\',\'BIG_DATA\':false},{\'VARIANT\':\'2\',\'BIG_DATA\':false},{\'VARIANT\':\'2\',\'BIG_DATA\':false},{\'VARIANT\':\'2\',\'BIG_DATA\':false},{\'VARIANT\':\'2\',\'BIG_DATA\':false},{\'VARIANT\':\'2\',\'BIG_DATA\':false},{\'VARIANT\':\'2\',\'BIG_DATA\':false},{\'VARIANT\':\'2\',\'BIG_DATA\':false}]',
        'ENLARGE_PRODUCT' => 'STRICT',
        'ENLARGE_PROP' => '',
        'SHOW_SLIDER' => 'Y',
        'SLIDER_INTERVAL' => '3000',
        'SLIDER_PROGRESS' => 'N',
        'OFFER_ADD_PICT_PROP' => NULL,
        'OFFER_TREE_PROPS' => [],
        'PRODUCT_SUBSCRIPTION' => 'N',
        'SHOW_DISCOUNT_PERCENT' => 'N',
        'DISCOUNT_PERCENT_POSITION' => NULL,
        'SHOW_OLD_PRICE' => 'N',
        'SHOW_MAX_QUANTITY' => 'N',
        'MESS_SHOW_MAX_QUANTITY' => '',
        'RELATIVE_QUANTITY_FACTOR' => '',
        'MESS_RELATIVE_QUANTITY_MANY' => '',
        'MESS_RELATIVE_QUANTITY_FEW' => '',
        'MESS_BTN_BUY' => 'Купить',
        'MESS_BTN_ADD_TO_BASKET' => 'В корзину',
        'MESS_BTN_SUBSCRIBE' => 'Подписаться',
        'MESS_BTN_DETAIL' => 'Подробнее',
        'MESS_NOT_AVAILABLE' => 'Нет в наличии',
        'MESS_BTN_COMPARE' => 'Сравнение',
        'USE_ENHANCED_ECOMMERCE' => 'N',
        'DATA_LAYER_NAME' => '',
        'BRAND_PROPERTY' => '',
        'TEMPLATE_THEME' => '',
        'ADD_SECTIONS_CHAIN' => 'Y',
        'ADD_TO_BASKET_ACTION' => NULL,
        'SHOW_CLOSE_POPUP' => 'N',
        'COMPARE_PATH' => '/catalog/compare/?action=#ACTION_CODE#',
        'COMPARE_NAME' => 'CATALOG_COMPARE_LIST',
        'USE_COMPARE_LIST' => 'Y',
        'BACKGROUND_IMAGE' => '-',
        'COMPATIBLE_MODE' => 'Y',
        'DISABLE_INIT_JS_IN_COMPONENT' => 'N',
      ],
      $component
    );
}
